CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  provider VARCHAR(50) DEFAULT 'google',
  provider_id VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  username VARCHAR(255) NOT NULL,
  picture TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);